pipeline {
    agent { label 'codeclarity' }

    environment {
        DOCKERHUB_CREDENTIALS=credentials('dockerhub')
    }
    stages {
        stage('Login') {
			steps {
				sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
                script {
                    def project =readJSON file: 'package.json'
                    env.Version = project.version
                    env.Name = project.name
                    sh 'echo $Version'
                    env.Tag = "parithera/${Name}:${Version}"
                    sh 'echo $Tag'
                }
			}
		}
        stage('Reset') {
            steps {
                sh 'docker system prune -af'
                sh 'git submodule update --init --recursive'
                sh 'git fetch --tags --force'
                sh 'yarn'
            }
        }
        stage('Test lint and format') {
            steps {
                sh 'yarn lint'
                sh 'yarn run vitest run'
                sh 'yarn run prettier src --check'
            }
        }
        stage('Build') {
            steps {
                sh 'docker buildx rm frontend || true'
                sh 'docker buildx create --name frontend --use --bootstrap'
                sh 'docker buildx build -f .cloud/docker/Dockerfile --platform linux/amd64 --tag parithera/frontend:latest --tag $Tag .'
            }
        }
        stage('Deploy') {
            when {
                branch 'main'
            }
            steps {
                script {
                    def result = sh(script: "sh .cloud/jenkins/check_version.sh ${Version}", returnStatus: true)
                    if (result == 0) {
                        sh 'docker buildx build -f .cloud/docker/Dockerfile --platform linux/amd64,linux/arm64 --tag parithera/frontend:latest --tag $Tag --push .'
                    }
                }
            }
        }
    }
}