services:
  frontend:
    build:
      context: ../../frontend
      dockerfile: .cloud/docker/Dockerfile
      target: frontend-dev
    restart: always
    volumes:
      - ../../frontend:/app:rw
    ports:
      - 5173:5173
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 200M

  caddy:
    image: caddy
    env_file:
      - ../../.cloud/env/.env.dev
    command: [ "caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile", "--watch" ]
    restart: always
    volumes:
      - ../../frontend/.cloud/docker/conf/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp
